# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wtp < Formula
  desc "Worktree Plus - Enhanced worktree management with automated setup and hooks"
  homepage "https://github.com/satococoa/wtp"
  version "1.1.0"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/satococoa/wtp/releases/download/v1.1.0/wtp_1.1.0_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "9cb102d597bcfea0e45ad9c7a7ba092198b7688db23264a422ef5c05152884e8"

      def install
        bin.install "wtp"
        generate_completions_from_executable(bin/"wtp", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/satococoa/wtp/releases/download/v1.1.0/wtp_1.1.0_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "a96ac3118c1eee5a1b220c8ee26a4b5b480fdba572110743356f3c99873f7f83"

        def install
          bin.install "wtp"
          generate_completions_from_executable(bin/"wtp", "completion")
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/satococoa/wtp/releases/download/v1.1.0/wtp_1.1.0_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "23cd3918bbd2e821e4c34961fbfa65fb10a86a88a0c6d1491718ca8daeeabb4c"

        def install
          bin.install "wtp"
          generate_completions_from_executable(bin/"wtp", "completion")
        end
      end
    end
  end

  test do
    system "#{bin}/wtp", "--help"
  end
end
