# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wtp < Formula
  desc "Worktree Plus - Enhanced worktree management with automated setup and hooks"
  homepage "https://github.com/satococoa/wtp"
  version "0.3.0-rc6"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/satococoa/wtp/releases/download/v0.3.0-rc6/wtp_0.3.0-rc6_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "7b007771a6ca326587b07f15fbf6b5a57a2cdc8d119c1648fbc264dcb9f878ff"

      def install
        bin.install "wtp"
        generate_completions_from_executable(bin/"wtp", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/satococoa/wtp/releases/download/v0.3.0-rc6/wtp_0.3.0-rc6_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "b5d1b5be5b379dfdd442abc0b65195f21a33aeb5b24cc21e311f505669cb768c"

        def install
          bin.install "wtp"
          generate_completions_from_executable(bin/"wtp", "completion")
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/satococoa/wtp/releases/download/v0.3.0-rc6/wtp_0.3.0-rc6_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "eed384033b4ab0a173930a199b0616de78ca20230feeb81ebb81a651c55be3f4"

        def install
          bin.install "wtp"
          generate_completions_from_executable(bin/"wtp", "completion")
        end
      end
    end
  end

  test do
    system "#{bin}/wtp", "--help"
  end
end
