# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wtp < Formula
  desc "Worktree Plus - Enhanced worktree management with automated setup and hooks"
  homepage "https://github.com/satococoa/wtp"
  version "0.3.0"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/satococoa/wtp/releases/download/v0.3.0/wtp_0.3.0_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "da09ac437b75a625517f62a2ec34ece3fe94d02e1438f19a1c40e614f5643484"

      def install
        bin.install "wtp"
        generate_completions_from_executable(bin/"wtp", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/satococoa/wtp/releases/download/v0.3.0/wtp_0.3.0_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "9d40806bd2ca56c11edf3d5ba38eac28f3a011280714f27ce08d0aad5041bfdd"

        def install
          bin.install "wtp"
          generate_completions_from_executable(bin/"wtp", "completion")
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/satococoa/wtp/releases/download/v0.3.0/wtp_0.3.0_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "7413c89aa3088247d6de84589f738511e3a0414182fd133e31f429c1140be675"

        def install
          bin.install "wtp"
          generate_completions_from_executable(bin/"wtp", "completion")
        end
      end
    end
  end

  test do
    system "#{bin}/wtp", "--help"
  end
end
